import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import ReactMarkdown from "react-markdown";
import {
  Lightbulb,
  Package,
  Cpu,
  Route,
  Megaphone,
  Gavel,
  ToggleLeft,
  ToggleRight,
  Copy,
  Check,
  RotateCcw,
  Star,
  Target,
  Zap,
  Eye,
  Trophy,
} from "lucide-react";

// Icons for co-founder mode tabs
const CO_FOUNDER_ICONS = [Lightbulb, Package, Cpu, Route, Megaphone];
const CO_FOUNDER_COLORS = [
  "text-yellow-400",
  "text-blue-400",
  "text-purple-400",
  "text-orange-400",
  "text-green-400",
];

// Icons for judge mode tabs
const JUDGE_ICONS = [Target, Zap, Cpu, Eye, Trophy];
const JUDGE_COLORS = [
  "text-red-400",
  "text-yellow-400",
  "text-purple-400",
  "text-blue-400",
  "text-green-400",
];

export default function ResultsPanel({
  results,
  judgeResults,
  judgeMode,
  onToggleJudgeMode,
  onReset,
  isLoadingJudge,
}) {
  const [activeTab, setActiveTab] = useState(0);
  const [copied, setCopied] = useState(false);

  const data = judgeMode ? judgeResults : results;
  const sections = data?.sections || [];
  const icons = judgeMode ? JUDGE_ICONS : CO_FOUNDER_ICONS;
  const colors = judgeMode ? JUDGE_COLORS : CO_FOUNDER_COLORS;

  const handleCopy = async () => {
    const raw = data?.raw || "";
    await navigator.clipboard.writeText(raw);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  // Reset active tab when switching modes
  const handleToggle = () => {
    setActiveTab(0);
    onToggleJudgeMode();
  };

  return (
    <section className="mx-auto max-w-5xl px-6 py-12">
      <motion.div
        initial={{ opacity: 0, y: 30 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
      >
        {/* Header */}
        <div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <h2 className="text-2xl font-bold text-white">
              {judgeMode ? "Judge Presentation" : "Your Startup Blueprint"}
            </h2>
            <p className="mt-1 text-sm text-gray-400">
              {judgeMode
                ? "Optimized for hackathon judges"
                : "Generated by your AI Co-Founder"}
            </p>
          </div>

          <div className="flex items-center gap-3">
            {/* Judge Mode Toggle */}
            <button
              onClick={handleToggle}
              disabled={isLoadingJudge}
              className={`flex items-center gap-2 rounded-xl border px-4 py-2.5 text-sm font-medium transition-all ${
                judgeMode
                  ? "border-amber-500/30 bg-amber-500/10 text-amber-400"
                  : "border-white/10 bg-gray-800/50 text-gray-400 hover:border-amber-500/20 hover:text-amber-400"
              }`}
            >
              {judgeMode ? (
                <ToggleRight className="h-5 w-5" />
              ) : (
                <ToggleLeft className="h-5 w-5" />
              )}
              <Gavel className="h-4 w-4" />
              Judge Mode
              {isLoadingJudge && (
                <div className="h-4 w-4 animate-spin rounded-full border-2 border-amber-400 border-t-transparent" />
              )}
            </button>

            {/* Copy */}
            <button
              onClick={handleCopy}
              className="flex items-center gap-2 rounded-xl border border-white/10 bg-gray-800/50 px-3 py-2.5 text-sm text-gray-400 transition-all hover:text-white"
              title="Copy to clipboard"
            >
              {copied ? (
                <Check className="h-4 w-4 text-green-400" />
              ) : (
                <Copy className="h-4 w-4" />
              )}
            </button>

            {/* Reset */}
            <button
              onClick={onReset}
              className="flex items-center gap-2 rounded-xl border border-white/10 bg-gray-800/50 px-3 py-2.5 text-sm text-gray-400 transition-all hover:text-white"
              title="Start over"
            >
              <RotateCcw className="h-4 w-4" />
            </button>
          </div>
        </div>

        {/* Main content card */}
        <div className="overflow-hidden rounded-2xl border border-white/10 bg-gray-900/50 backdrop-blur-sm">
          {/* Tabs */}
          {sections.length > 0 && (
            <div className="flex overflow-x-auto border-b border-white/5 bg-gray-900/80">
              {sections.map((section, i) => {
                const Icon = icons[i] || Star;
                const color = colors[i] || "text-gray-400";
                return (
                  <button
                    key={i}
                    onClick={() => setActiveTab(i)}
                    className={`flex min-w-fit items-center gap-2 px-5 py-3.5 text-sm font-medium transition-all ${
                      activeTab === i
                        ? `${color} tab-active bg-white/5`
                        : "text-gray-500 hover:bg-white/[0.03] hover:text-gray-300"
                    }`}
                  >
                    <Icon className="h-4 w-4" />
                    <span className="whitespace-nowrap">{section.title}</span>
                  </button>
                );
              })}
            </div>
          )}

          {/* Tab content */}
          <div className="p-6 sm:p-8">
            <AnimatePresence mode="wait">
              {sections.length > 0 && sections[activeTab] && (
                <motion.div
                  key={`${judgeMode}-${activeTab}`}
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -10 }}
                  transition={{ duration: 0.2 }}
                  className="markdown-content"
                >
                  <ReactMarkdown>{sections[activeTab].content}</ReactMarkdown>
                </motion.div>
              )}
            </AnimatePresence>

            {/* If no sections parsed, show raw */}
            {sections.length === 0 && data?.raw && (
              <div className="markdown-content">
                <ReactMarkdown>{data.raw}</ReactMarkdown>
              </div>
            )}

            {/* Judge mode loading placeholder */}
            {judgeMode && isLoadingJudge && !judgeResults && (
              <div className="flex flex-col items-center justify-center py-12">
                <div className="mb-4 h-10 w-10 animate-spin rounded-full border-2 border-amber-400 border-t-transparent" />
                <p className="text-sm text-gray-400">
                  Preparing your judge presentation...
                </p>
              </div>
            )}
          </div>
        </div>

        {/* Bottom info */}
        <div className="mt-4 flex items-center justify-center gap-2 text-xs text-gray-600">
          <Cpu className="h-3 w-3" />
          Generated using Google Gemini — multi-step reasoning
        </div>
      </motion.div>
    </section>
  );
}
